name: CI
on:
  pull_request:
  push:
    branches: [main]
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  license:
    uses: oas-ai/.github/.github/workflows/license-check.yml@main
  python:
    uses: oas-ai/.github/.github/workflows/python-ci.yml@main
